name: CI development
on: push
jobs:
  run:
    name: Full tests on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]#, "macos-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow --tags
    - uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.8
    - name: Install this package, on development mode
      env:
          NWB_CONVERSION_INSTALL_MODE: development
      run: pip install .
    - name: Get ephy_testing_data current head hash
      id: vars
      run: echo "::set-output name=HASH_EPHY_DATASET::$(git ls-remote https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.git HEAD | cut -f1)"
    - uses: actions/cache@v2
      id: cache-datasets
      with:
        path: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/ephy_testing_data
        key: ecephys-dset-${{ steps.vars.outputs.HASH_EPHY_DATASET }}
        restore-keys: |
          ecephys-dset-${{ steps.vars.outputs.HASH_EPHY_DATASET }}
    - name: Test with pytest
      run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=/home/runner/work/nwb-conversion-tools --cov-report=xml
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: codecov_xml
        path: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/coverage.xml
    - if: ${{ matrix.os }} == "ubuntu-latest"
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/coverage.xml
        flags: unittests
        name: codecov-umbrella 
        yml: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/codecov.yml
