name: Full tests on Mac
on: pull_request
jobs:
  run:
    name: Full tests on ${{ matrix.os }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install nwb-conversion-tools, full requirements, and pytest
        run: |
          pip install -e .
          pip install -r requirements-full.txt
          pip install pytest
      - name: Get ephy_testing_data current head hash
        id: ephys
        run: echo "::set-output name=HASH_EPHY_DATASET::$(git ls-remote https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.git HEAD | cut -f1)"
      # - name: Cache ephys dataset - ${{ steps.ephys.outputs.HASH_EPHYS_DATASET }}
      #   uses: actions/cache@v2
      #   id: cache-datasets
      #   with:
      #     path: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/ephy_testing_data
      #     key: ecephys-datasets-3-${{ steps.ephys.outputs.HASH_EPHY_DATASET }}
      #     restore-keys: ecephys-datasets-3-${{ steps.ephys.outputs.HASH_EPHY_DATASET }}
      # - name: Run pytest with GIN data
      #   if: steps.cache-datasets.outputs.cache-hit == true
      #   run: pytest
      - name: Run pytest without GIN data
        # if: steps.cache-datasets.outputs.cache-hit == false
        run: pytest tests/test_internals
