name: Minimal and full tests on Mac
on: pull_request
jobs:
  run:
    name: Minimal and full tests on Mac with Python ${{ matrix.python-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest
        run: |
          pip install pytest
          pip install pytest-cov

      - name: Install nwb-conversion-tools with minimal requirements
        run: pip install -e .
      - name: Run minimal pytest with coverage
        run: pytest tests/test_internals --cov=./ --cov-report xml:./nwb-conversion-tools/nwb-conversion-tools/minimal-coverage.xml
      - name: Upload minimal coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./nwb-conversion-tools/nwb-conversion-tools/minimal-coverage.xml
          flags: unittests
          name: codecov-umbrella 
          yml: ./nwb-conversion-tools/nwb-conversion-tools/codecov.yml

      - name: Install full requirements
        run: pip install -r requirements-full.txt
      # - name: Get ephy_testing_data current head hash
      #   id: ephys
      #   run: echo "::set-output name=HASH_EPHY_DATASET::$(git ls-remote https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.git HEAD | cut -f1)"
      # - name: Cache ephys dataset - ${{ steps.ephys.outputs.HASH_EPHYS_DATASET }}
      #   uses: actions/cache@v2
      #   id: cache-datasets
      #   with:
      #     path: /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/ephy_testing_data
      #     key: ecephys-datasets-3-${{ steps.ephys.outputs.HASH_EPHY_DATASET }}
      #     restore-keys: ecephys-datasets-3-${{ steps.ephys.outputs.HASH_EPHY_DATASET }}
      # - name: Run pytest with GIN data
      #   if: steps.cache-datasets.outputs.cache-hit == true
      #   run: pytest
      - name: Run pytest without GIN data
        # if: steps.cache-datasets.outputs.cache-hit == false
        run: pytest tests/test_internals
